# Reload config
bind r source-file ~/.config/tmux/tmux.conf \; display-message "tmux.conf reloaded"

# Mouse support
set -g mouse on

# Pane quick cycling
bind -n M-/ select-pane -t :.+

# Bottom status bar
set -g status-position bottom

# Kill current session
bind x kill-session
